# Generated by Django 3.1.4 on 2020-12-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201218_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='eamil',
            new_name='email',
        ),
    ]
